### PR TITLE
Revert "I33 scroll to top"

### PR DESCRIPTION
**Pull request by tz-goat**
Reverts FreeOpenUniversity/website-frontend#37

### CODE REVIEW

**Comment by tz-goat** [comment]
Sorry to bother you guys, can any of you approve my request so I can finish the revert merge, I only need two approvings

**Review by vrcode-dev — APPROVED** [review]
Ok

**Comment by IsraOsman** [comment]
Sure, thank you.

**Review by IsraOsman — APPROVED** [review]

**Review by Iancam — APPROVED** [review]
looks fine to me.

**Pull request merged**
